---
Name: simplebookingconfig
---

# Extensions
SilverCommerce\OrdersAdmin\Model\Invoice:
  extensions:
    - ilateral\SimpleBookings\Extensions\InvoiceExtension
SilverCommerce\OrdersAdmin\Model\LineItem:
  extensions:
    - ilateral\SimpleBookings\Extensions\LineItemExtension